security:
    password_hashers:
        App\Entity\Utilisateur: 'auto'
    providers:
        utilisateur_provider:
            id: App\Security\UtilisateurProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: utilisateur_provider
            access_denied_handler: App\Security\AccessDeniedHandler
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/signup, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        # CRUD PROTECTIONS
        - { path: '^/adresse/new', roles: ROLE_ADMIN }
        - { path: '^/adresse/\d+/edit', roles: ROLE_ADMIN }
        - { path: '^/adresse/\d+$', methods: [POST, DELETE], roles: ROLE_ADMIN }
        
        - { path: '^/categorie/new', roles: ROLE_ADMIN }
        - { path: '^/categorie/\d+/edit', roles: ROLE_ADMIN }
        - { path: '^/categorie/\d+$', methods: [POST, DELETE], roles: ROLE_ADMIN }
        
        - { path: '^/lieu/touristique/new', roles: ROLE_ADMIN }
        - { path: '^/lieu/touristique/\d+/edit', roles: ROLE_ADMIN }
        - { path: '^/lieu/touristique/\d+$', methods: [POST, DELETE], roles: ROLE_ADMIN }
        - { path: '^/lieu/touristique/\d+/toggle-status', roles: ROLE_ADMIN }
        - { path: '^/lieu/touristique/\d+/duplicate', roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
